### PR TITLE
Simple HEAD support for icy-name in /get_song

### PR DESCRIPTION
**Pull request by gdhgdhgdh**
I'll be working on changes to the Logitech Media Server to make it smarter when working with a playlist of HTTP streams.

Currently it will only retrieve metadata when a track is actually played, leading to a playlist full of 'No Artist / No Title'. Very ugly and useless for managing a party playlist.

I will be hacking in `HEAD` support to get metadata when a new HTTP stream is added to the Logitech Media Server, and this PR is to support the GMusicProxy side of that work.

### CODE REVIEW

**Comment by diraimondo** [comment]
In order to keep at minimum the redundant code, I rewrote your code. All the requested functionality should be present now. Please, test latest commits and let me know if it works for you.

**Comment by gdhgdhgdh** [comment]
Excellent, thank you! :)

My main comment would be the ordering of the output is now rather odd, e.g.

```icy-name: Whatever And Ever Amen (Remastered Edition) / Ben Folds Five / Brick```

`Album / Artist / Title` seems an odd ordering compared to `Artist / Album / Tiitle`.  Can I suggest also `///` as a delimiter since I'll only end up parsing the string back into separate fields :)

**Comment by diraimondo** [comment]
Ok, test latest commit.

**Comment by gdhgdhgdh** [comment]
Awesome - thanks :)

**Pull request closed without merging**
